### ISSUE TITLE
https://github.com/rtonata88/burrito-scores

### ISSUE THREAD

**Issue by rtonata88** [rtonata88/burrito-scores#21]
There are 2 members in our group
Student A - Richard Chambula (@rtonata88)
Student B - Manuel Aldaraca (@vicmaburrito)

**Comment by D4nielJ** [comment]
## Hello @rtonata88 and @vicmaburrito, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

![](https://i.imgur.com/NLzCKYy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
